version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.4
  codecov: codecov/codecov@1.0.2

jobs:
    build-and-test:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout

        - setup_remote_docker:
            docker_layer_caching: true

        - run:
            name: Build docker image
            command: >
              docker build -t ismikin/matcher-py:${CIRCLE_WORKFLOW_ID} .

        - run:
            name: Build expanded image with test stuff included
            command: |
              docker build -f .circleci/test.Dockerfile \
                --build-arg baseImage=ismikin/matcher-py:${CIRCLE_WORKFLOW_ID} \
                -t ismikin/matcher-py:${CIRCLE_WORKFLOW_ID}-test-img .

        - run:
            name: Run tests
            command: |
              docker run  \
                --name test-run \
                ismikin/matcher-py:${CIRCLE_WORKFLOW_ID}-test-img

        # Repeat tests to upload to coveralls
        # FIXME: it because the source changes, so inside the docker it's
        # on /src so it doesnt match with the repo file structure
        - run:
            name: Copy out test reports and upload to Coveralls
            when: always
            command: |
              echo "Copy report files from docker test container"
              docker cp test-run:/src/test-reports/. test-reports
              ls test-reports
              sudo pip install pipenv
              pipenv install --dev
              pipenv run coverage run --source=matcher/,matcher/score,matcher/data -m pytest --strict -rw --ignore=venv/ --cache-clear
              pipenv run coverage xml -o coverage.xml
              echo "Run coveralls"
              pipenv run coveralls

        - codecov/upload:
            file: /home/circleci/project/test-reports/.coverage

        - store_test_results:
            path: test-reports



workflows:
  version: 2.1
  build_without_publishing_job:
    jobs:
      - build-and-test
      - docker-publish/publish:
          requires:
            - build-and-test
          deploy: false
          tag: latest
          filters:
            branches:
              ignore: master

  docker_with_lifecycle:
    jobs:
      - build-and-test:
          filters:
            branches:
             only: master
      - docker-publish/publish:
          requires:
            - build-and-test
          tag: latest
          filters:
            branches:
             only: master
