version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.4

jobs:
    build_and_test:
      docker:
        - image: circleci/python:3
      steps:
        - checkout

        - setup_remote_docker:
            docker_layer_caching: true
            
        - run:
            name: Build docker image
            command: |
              export BRANCH_NAME_CLEAN=${CIRCLE_BRANCH/\//-}
              export SHORT_WORKFLOW_ID=`echo $long_string | tail -c 5`
              export IMG_TAG_VERSION=$BRANCH_NAME_CLEAN:${CIRCLE_WORKFLOW_ID}
              docker build -t ismikin/matcher-py:${IMG_TAG_VERSION} .

        - run:
            name: Build expanded image with test stuff included
            command: |
              docker build -f .circleci/test.Dockerfile \
                --build-arg baseImage=ismikin/matcher-py:${IMG_TAG_VERSION} \
                -t ismikin/matcher-py:${IMG_TAG_VERSION}-test-img .

        - run:
            name: Run tests
            command: |
              docker run  \
                --name test-run \
                ismikin/matcher-py:${IMG_TAG_VERSION}-test-img

        - run:
            name: Copy out test reports
            when: always
            command: |
              docker cp test-run:/src/test-reports/. test-reports

        - store_test_results:
            path: test-reports


workflows:
  docker_ci:
    jobs:
      - build_and_test
      - docker-publish/publish:
          requires:
            - build_and_test
