"""Init revision

Revision ID: 1bbb662eefdb
Revises:
Create Date: 2019-01-21 17:54:27.937849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbb662eefdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_processed',
    sa.Column('hash', sa.Text(), server_default=sa.text("nextval('files_processed_hash_seq'::regclass)"), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_time_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('sound_recordings',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('sound_recordings_id_seq'::regclass)"), nullable=False),
    sa.Column('artist', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sound_record_match',
    sa.Column('match_id', sa.Text(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('isrc', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('files_processed_FK', sa.Text(), nullable=False),
    sa.Column('sound_recordings_FK', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['files_processed_FK'], ['files_processed.hash'], ),
    sa.ForeignKeyConstraint(['sound_recordings_FK'], ['sound_recordings.id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sound_record_match')
    op.drop_table('sound_recordings')
    op.drop_table('files_processed')
    # ### end Alembic commands ###
